# Server
server.port=8080
server.servlet.context-path=/api

# Internacionalização
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Datasource
spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm556331
spring.datasource.password=151005
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# IA - Spring AI
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.model=openai/gpt-3.5-turbo

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Segurança (usuário padrão do Spring Security)
spring.security.user.name=admin
spring.security.user.password=admin123

# JWT
jwt.secret=c2tpbGw0Z3JlZW4tc2VjcmV0LWtleS1wYXJhLWp3dC0yNTZiaXRz

# Cache
spring.cache.type=simple

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Paginação padrão
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=50

# Testes e Dev
spring.devtools.restart.enabled=true
spring.main.allow-bean-definition-overriding=true



spring.jpa.open-in-view=false